### PR TITLE
ds-jupyter-lab: renamed from ds-jupyter-notebook and updates on quickstarter notes

### PR DESCRIPTION
**Pull request by gerardcl**
Relates and Fixes https://github.com/opendevstack/ods-quickstarters/issues/562

### CODE REVIEW

**Review by michaelsauter — COMMENTED** [review]
Fine by me. @metmajer @borja44 If you don't object, let's move forward with this and please make a note to update required doc.

**Comment by borja44** [comment]
Fine for me @michaelsauter

**Review by borja44 — DISMISSED** [review]
approve renaming of quickstarter

**Review by borja44 — APPROVED** [review]
Reviewed

**Review by borja44 — APPROVED** [review]

**Pull request merged**
