### PR TITLE
Removes existing differences between jenkins agent base image in Centos 7 and UBI 8 

### PR DESCRIPTION
**Pull request by victorpablosceruelo**
Removes existing differences between jenkins agent base image in Centos 7 and UBI 8 which, for example, cause different behaviour when running quickstaters.

- [x] jre not found by Jenkins agents when launched. In Centos7 images, install jre 11 and uninstall deprecated jre 8. 
- [x] default value for JAVA_TOOL_OPTIONS has UseCGroupMemoryLimitForHeap, which is deprecated in jre 11 and cannot be used. In UBI 8 base images this default value is not set. Remove it from Centos 7 base img for agents.
- [x] default value for JAVA_GC_OPTS contains `-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90`. Some of the options are incompatible with the options proposed in https://github.com/opendevstack/ods-core/pull/1161 (`-server -XX:NativeMemoryTracking=summary -XX:MaxRAMPercentage=90 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=256M -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1
-Xmx4g`). Although we do not use all that options for agents pods, we cannot afford setting contradictory options. 
- [x] smoke tests fail during ods box creation. Reason: the default parameters for JAVA_TOOL_OPTIONS and JAVA_GC_OPTS 
- [x] Not set default speed/durability setting to SURVIVABLE_NONATOMIC (as requested in https://github.com/opendevstack/ods-core/pull/1161 ). Seems to be the script is missing some imports.
- [x] The [Config.NameToCertificate](https://go.dev/pkg/crypto/tls/#Config.NameToCertificate) field, which only supports associating a single certificate with a give name, is now deprecated and should be left as nil. https://go.dev/pkg/crypto/tls/
- [x] When an error occurs running a quickstarter or smoke test and we cannot retrieve the logs, wait for manual intervention (at most 24h). Some issues need much more information than the one we retrieve in logs and it is faster allowing to connect to the boxes at that point in the execution flow.

### CODE REVIEW

**Comment by victorpablosceruelo** [comment]
@jafarre-bi @braisvq1996 

Right now we are having 2 problems.

1st one: we are trying to obtain the jenkins master log with the openshift user instead of with the developer user and he has no admin rights in Jenkins (he cannot retrieve that logs). I had to enter the box to retrieve the following info and this is the cause. We need to fix this so we do not have to enter the temporary boxes to do this.

2nd one: the log I'm attaching shows there might be a syntax error (  Unrecognized VM option 'UseCGroupMemoryLimitForHeap'  )  or maybe we are right now forced to upgrade the Boxes Jenkins version...

```
Sep 07, 2022 3:26:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Template for label create-projects-odsverify: Kubernetes Pod Template
Sep 07, 2022 3:26:30 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Created Pod: ods/create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:31 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Pod is running: ods/create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:31 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Waiting for agent to connect (0/100): create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:32 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Waiting for agent to connect (1/100): create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:33 PM SEVERE org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher logLastLines
Error in provisioning; agent=KubernetesSlave name: create-projects-odsverify-vxrq7-wr1h3, template=PodTemplate{, name='create-projects-odsverify-vxrq7', namespace='ods', label='create-projects-odsverify', serviceAccount='jenkins', nodeUsageMode=EXCLUSIVE, containers=[ContainerTemplate{name='jnlp', image='docker-registry.default.svc:5000/ods/jenkins-agent-base:latest', alwaysPullImage=true, workingDir='/tmp', args=''}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}. Container jnlp. Logs: INFO: importing into cacerts
Warning: use -cacerts option to access cacerts keystore
Certificate was added to keystore
[Storing /usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.el7_9.x86_64/lib/security/cacerts]
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.
ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.
alternatives version 1.7.6 - Copyright (C) 2001 Red Hat, Inc.
This may be freely redistributed under the terms of the GNU Public License.

usage: alternatives --install <link> <name> <path> <priority>
                    [--initscript <service>]
                    [--family <family>]
                    [--slave <link> <name> <path>]*
       alternatives --remove <name> <path>
       alternatives --auto <name>
       alternatives --config <name>
       alternatives --display <name>
       alternatives --set <name> <path>
       alternatives --list

common options: --verbose --test --help --usage --version --keep-missing
                --altdir <directory> --admindir <directory>
OPENSHIFT_JENKINS_JVM_ARCH='', CONTAINER_MEMORY_IN_MB='8796093022207', using /usr/lib/jvm/java-11-openjdk-11.0.16.0.8-1.el7_9.x86_64/bin/java
Downloading http://jenkins.ods.svc:80//jnlpJars/remoting.jar ...
+ cd
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -cp /home/jenkins/remoting.jar hudson.remoting.jnlp.Main -headless -url http://jenkins.ods.svc:80/ -tunnel jenkins-jnlp.ods.svc:50000 4483607290cb134d487dd1dab449bd46744d1f5e4b6ae0c61e85e0ac7a61d068 create-projects-odsverify-vxrq7-wr1h3
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Sep 07, 2022 3:26:33 PM WARNING org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Error in provisioning; agent=KubernetesSlave name: create-projects-odsverify-vxrq7-wr1h3, template=PodTemplate{, name='create-projects-odsverify-vxrq7', namespace='ods', label='create-projects-odsverify', serviceAccount='jenkins', nodeUsageMode=EXCLUSIVE, containers=[ContainerTemplate{name='jnlp', image='docker-registry.default.svc:5000/ods/jenkins-agent-base:latest', alwaysPullImage=true, workingDir='/tmp', args=''}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}
java.lang.IllegalStateException: Agent is not connected after 2 seconds, status: Failed
	at org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher.launch(KubernetesLauncher.java:190)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:291)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:71)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Sep 07, 2022 3:26:33 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Terminating Kubernetes instance for agent create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:33 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave deleteSlavePod
Terminated Kubernetes instance for agent ods/create-projects-odsverify-vxrq7-wr1h3
Sep 07, 2022 3:26:33 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesSlave _terminate
Disconnected computer create-projects-odsverify-vxrq7-wr1h3

```

From:
[jenkins-master-log.txt](https://github.com/opendevstack/ods-core/files/9507629/jenkins-master-log.txt)

**Comment by clemensutschig** [comment]
I am wondering what creates the vm with those settings? 

Von meinem iPhone gesendet

**Comment by victorpablosceruelo** [comment]
Hi Clemens.

Yes, me too...

Seems to be it is not being us...

image

Thinking on it, I see at least two possible causes: Jenkins has that options or the Jenkins docker container we are using has them and Jenkins inherits them. I'll start looking for them right now.

Will keep u informed. Thanks.

**Comment by michaelsauter** [comment]
Just a drive by comment - IIRC there is a lot of funky stuff in the Jenkins base image provided by RedHat that sets these params, also based on the situation (e.g. based on available memory). I believe there were similar issues in the past but I could not find it in the search now ...

**Comment by victorpablosceruelo** [comment]
> Just a drive-by comment - IIRC there is a lot of funky stuff in the Jenkins base image provided by RedHat that sets these params, also based on the situation (e.g. based on available memory). I believe there were similar issues in the past but I could not find it in the search now ...

Yep. There is where I'm looking right now...
But it seems they knew about it and tried to remove that stuff.

Maybe we need to get rid of that param in the slave launch script...

image

A filter here could be our solution to the problem...

**Comment by victorpablosceruelo** [comment]
Mmmmmm

I'm including the following file, which is run when an agent is launched.

[run_jnlp_agent.txt](https://github.com/opendevstack/ods-core/files/9524752/run_jnlp_agent.txt)

```
# Configure the slave image
source /usr/local/bin/configure-slave
source /usr/local/bin/configure-agent
```

Could it be that?

**Comment by victorpablosceruelo** [comment]
Need to look somewhere else...

image

**Comment by victorpablosceruelo** [comment]
The error we are getting is caused by using java 11 for the slaves, which will be mandatory rather soon (already had to upgrade the microbox images used to build the boxes images because Jenkins stopped working with them).

We introduced the change from java 8 to java 11 here. Just for reference.
https://github.com/opendevstack/ods-core/pull/1180/files

**Comment by victorpablosceruelo** [comment]
We have a new log from Jenkins master:

[jenkins-master-log-with-debug.txt](https://github.com/opendevstack/ods-core/files/9527017/jenkins-master-log-with-debug.txt)

```
Error in provisioning; agent=KubernetesSlave name: create-projects-odsverify-5m7jg-wm8r1, template=PodTemplate{, name='create-projects-odsverify-5m7jg', namespace='ods', label='create-projects-odsverify', serviceAccount='jenkins', nodeUsageMode=EXCLUSIVE, containers=[ContainerTemplate{name='jnlp', image='docker-registry.default.svc:5000/ods/jenkins-agent-base:latest', alwaysPullImage=true, workingDir='/tmp', args=''}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}. Container jnlp. Logs: + PARAMS=
+ [[ 0913ea9468a7fb06b32c0aeb1ee8281d812b62f3542e9ca21791fbc363471ed7 create-projects-odsverify-5m7jg-wm8r1 != *\-\u\r\l\ * ]]
+ '[' '!' -z http://jenkins.ods.svc:80/ ']'
+ PARAMS=' -url http://jenkins.ods.svc:80/'
Downloading http://jenkins.ods.svc:80//jnlpJars/remoting.jar ...
+ echo 'Downloading http://jenkins.ods.svc:80//jnlpJars/remoting.jar ...'
+ curl -sS http://jenkins.ods.svc:80//jnlpJars/remoting.jar -o /home/jenkins/remoting.jar
+ [[ 0913ea9468a7fb06b32c0aeb1ee8281d812b62f3542e9ca21791fbc363471ed7 create-projects-odsverify-5m7jg-wm8r1 != *\-\t\u\n\n\e\l\ * ]]
+ '[' '!' -z jenkins-jnlp.ods.svc:50000 ']'
+ PARAMS=' -url http://jenkins.ods.svc:80/ -tunnel jenkins-jnlp.ods.svc:50000'
+ [[ -z '' ]]
+ JAVA_TOOL_OPTIONS='-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true'
+ export JAVA_TOOL_OPTIONS
+ [[ 9223372036854771712 -lt 1099511627776 ]]
+ [[ -z '' ]]
+ JAVA_GC_OPTS='-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90'
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z '' ]]
+ JNLP_JAVA_OPTIONS='-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90    '
+ read -a JNLP_JAVA_OVERRIDES_ARRAY
+ set -x
+ cd
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -cp /home/jenkins/remoting.jar hudson.remoting.jnlp.Main -headless -url http://jenkins.ods.svc:80/ -tunnel jenkins-jnlp.ods.svc:50000 0913ea9468a7fb06b32c0aeb1ee8281d812b62f3542e9ca21791fbc363471ed7 create-projects-odsverify-5m7jg-wm8r1
Picked up JAVA_TOOL_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
Unrecognized VM option 'UseCGroupMemoryLimitForHeap'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

The script seems to be running the lines
```
+ JAVA_TOOL_OPTIONS='-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true'
+ export JAVA_TOOL_OPTIONS
```

It is, at least, strange...

**Comment by victorpablosceruelo** [comment]
This is the file we are running for Centos 7. Why it is not equal to the one we have for UBI 8 ?

[openshift-run-jnlp-client_contents.txt](https://github.com/opendevstack/ods-core/files/9527136/openshift-run-jnlp-client_contents.txt)

The important lines that are being a problem:
```
  if [[ -z "${JAVA_TOOL_OPTIONS}" ]]; then
    # these options will automatically be picked up by any JVM process but can
    # be overridden on that process' command line.
    JAVA_TOOL_OPTIONS="-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true"
    export JAVA_TOOL_OPTIONS
  fi

```

**Comment by victorpablosceruelo** [comment]
The uses of the variable that I see seem to accept this variable is unset, but it is not unset.

image

Maybe if we just unset (by removing its set in [openshift-run-jnlp-client_contents.txt](https://github.com/opendevstack/ods-core/files/9527136/openshift-run-jnlp-client_contents.txt) ) it we succeed...

**Comment by victorpablosceruelo** [comment]
Still some problems with agents base image...

```
Sep 08, 2022 9:49:50 PM INFO org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
OpenShift OAuth: provider: OpenShiftProviderInfo: issuer: https://ocp.odsbox.lan:8443 auth ep: https://ocp.odsbox.lan:8443/oauth/authorize token ep: https://ocp.odsbox.lan:8443/oauth/token
Sep 08, 2022 9:49:50 PM INFO org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm useProviderOAuthEndpoint
OpenShift OAuth the server is 3.x, specifically OpenShiftVersionInfo: major: 1 minor: 11+ gitVersion: v1.11.0+d4cacc0
Sep 08, 2022 9:49:50 PM INFO org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm populateDefaults
OpenShift OAuth returning true with namespace ods SA dir null default /run/secrets/kubernetes.io/serviceaccount SA name null default jenkins client ID null default system:serviceaccount:ods:jenkins secret null default eyJhb....... redirect null default https://ocp.odsbox.lan:8443 server null default https://kubernetes.default:443
Sep 08, 2022 9:49:50 PM INFO org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm getRoleToPermissionMap
OpenShift Jenkins Login Plugin could not find the openshift-jenkins-login-plugin-config config map in namespace ods so the default permission mapping will be used
Sep 08, 2022 9:49:50 PM INFO org.openshift.jenkins.plugins.openshiftlogin.OpenShiftOAuth2SecurityRealm updateAuthorizationStrategy
OpenShift OAuth: adding permissions for user developer, stored in the matrix as developer-admin-edit-view, based on OpenShift roles [admin, edit, view]
Sep 08, 2022 9:49:52 PM INFO jenkins.slaves.JnlpSlaveAgentProtocol3$Impl allows
Inbound TCP Agent Protocol/3 has been forcibly disabled for additional security reasons. To enable it yet again set the system property jenkins.slaves.JnlpSlaveAgentProtocol3.ALLOW_UNSAFE
Sep 08, 2022 9:49:56 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Excess workload after pending Kubernetes agents: 1
Sep 08, 2022 9:49:56 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Template for label create-projects-odsverify: Kubernetes Pod Template
Sep 08, 2022 9:49:56 PM INFO hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
Started provisioning Kubernetes Pod Template from openshift with 1 executors. Remaining excess workload: 0
Sep 08, 2022 9:50:06 PM INFO hudson.slaves.NodeProvisioner lambda$update$6
Kubernetes Pod Template provisioning successfully completed. We have now 2 computer(s)
Sep 08, 2022 9:50:06 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Excess workload after pending Kubernetes agents: 0
Sep 08, 2022 9:50:06 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud provision
Template for label create-projects-odsverify: Kubernetes Pod Template
Sep 08, 2022 9:50:06 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Created Pod: ods/create-projects-odsverify-7mnqg-kkd2s
Sep 08, 2022 9:50:08 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Pod is running: ods/create-projects-odsverify-7mnqg-kkd2s
Sep 08, 2022 9:50:08 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Waiting for agent to connect (0/100): create-projects-odsverify-7mnqg-kkd2s
Sep 08, 2022 9:50:09 PM INFO org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher launch
Waiting for agent to connect (1/100): create-projects-odsverify-7mnqg-kkd2s
Sep 08, 2022 9:50:10 PM SEVERE org.csanchez.jenkins.plugins.kubernetes.KubernetesLauncher logLastLines
Error in provisioning; agent=KubernetesSlave name: create-projects-odsverify-7mnqg-kkd2s, template=PodTemplate{, name='create-projects-odsverify-7mnqg', namespace='ods', label='create-projects-odsverify', serviceAccount='jenkins', nodeUsageMode=EXCLUSIVE, containers=[ContainerTemplate{name='jnlp', image='docker-registry.default.svc:5000/ods/jenkins-agent-base:latest', alwaysPullImage=true, workingDir='/tmp', args=''}], annotations=[org.csanchez.jenkins.plugins.kubernetes.PodAnnotation@aab9c821]}. Container jnlp. Logs: ++ awk '{print NF}'
+ [[ 2 -gt 1 ]]
+ JAR=/home/jenkins/remoting.jar
+ PARAMS=
Downloading http://jenkins.ods.svc:80//jnlpJars/remoting.jar ...
+ [[ fe9d3808dd536a8ae157a4e97b8f297a96ff491d507cac2aa650360197c214b8 create-projects-odsverify-7mnqg-kkd2s != *\-\u\r\l\ * ]]
+ '[' '!' -z http://jenkins.ods.svc:80/ ']'
+ PARAMS=' -url http://jenkins.ods.svc:80/'
+ echo 'Downloading http://jenkins.ods.svc:80//jnlpJars/remoting.jar ...'
+ curl -sS http://jenkins.ods.svc:80//jnlpJars/remoting.jar -o /home/jenkins/remoting.jar
+ [[ fe9d3808dd536a8ae157a4e97b8f297a96ff491d507cac2aa650360197c214b8 create-projects-odsverify-7mnqg-kkd2s != *\-\t\u\n\n\e\l\ * ]]
+ '[' '!' -z jenkins-jnlp.ods.svc:50000 ']'
+ PARAMS=' -url http://jenkins.ods.svc:80/ -tunnel jenkins-jnlp.ods.svc:50000'
+ [[ -z -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true ]]
+ [[ 9223372036854771712 -lt 1099511627776 ]]
+ [[ -z '' ]]
+ JAVA_GC_OPTS='-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90'
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -z '' ]]
+ JNLP_JAVA_OPTIONS='-XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90    '
+ read -a JNLP_JAVA_OVERRIDES_ARRAY
+ set -x
+ cd
+ exec java -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -cp /home/jenkins/remoting.jar hudson.remoting.jnlp.Main -headless -url http://jenkins.ods.svc:80/ -tunnel jenkins-jnlp.ods.svc:50000 fe9d3808dd536a8ae157a4e97b8f297a96ff491d507cac2aa650360197c214b8 create-projects-odsverify-7mnqg-kkd2s
Picked up JAVA_TOOL_OPTIONS: -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockDiagnosticVMOptions -XX:+UnlockExperimentalVMOptions -Dsun.zip.disableMemoryMapping=true
Error occurred during initialization of VM
Multiple garbage collectors selected
```

At least we found where the other option was set...

And this seems to be easy. We just need to disable the variable JAVA_GC_OPTS too...

**Review by angelmp01 — APPROVED** [review]

**Review by angelmp01 — APPROVED** [review]

**Review by braisvq1996 — APPROVED** [review]

**Review by jafarre-bi — APPROVED** [review]

**Pull request merged**
