### PR TITLE
add aws quickstarter into the Prov-app Config Map

### PR DESCRIPTION
**Pull request by braisvq1996**
Update the Config Map of the Prov-app with the new AWS Terraform quickstarter

Follow up of https://github.com/opendevstack/ods-quickstarters/pull/565

@michaelsauter @metmajer @clemensutschig @gerardcl

We have made the Pull request in your behalf @nichtraunzer

### CODE REVIEW

**Comment by nichtraunzer** [comment]
nice 👍

**Comment by stitakis** [comment]
@nichtraunzer congrats to the AWS quickstarter team! Glad to see the fruits of all supporting sessions! PR looks good to me!

**Review by stitakis — APPROVED** [review]

**Review by gerardcl — APPROVED** [review]

**Review by michaelsauter — APPROVED** [review]

**Comment by michaelsauter** [comment]
Is this intended to go into 3.x, or should this rather be master?

**Comment by metmajer** [comment]
@michaelsauter @braisvq1996 we'd for sure need both please!

**Comment by michaelsauter** [comment]
@metmajer note that existing 3.x installations can (and actually have to) always add this to the config manually. Making the change like in this PR only has an effect on new installations ...

**Comment by braisvq1996** [comment]
@metmajer - We can also prepare another PR to master for this and https://github.com/opendevstack/ods-quickstarters/pull/570

**Pull request merged**
