### PR TITLE
Externalize sonarqube download url

### PR DESCRIPTION
**Pull request by stitakis**
PR for branch 1.1.x, feature #123

### CODE REVIEW

**Comment by clemensutschig** [comment]
@stitakis  - this is a breaking change I would say ... so it should go only into master
@michaelsauter  what do you think?

**Comment by gerardcl** [comment]
@clemensutschig I moved this task to `In Progress` since this should come with the related updates in the related `ods-configuration/-sample` as aforementioned

**Comment by stitakis** [comment]
thanks... changes in sample config is missing

**Comment by stitakis** [comment]
@gerardcl example added as PR: https://github.com/opendevstack/ods-configuration-sample/pull/35

**Comment by stitakis** [comment]
@clemensutschig @michaelsauter yes, change is a breaking one and is already deployed in BIX bitbucket production branch and openshift. Should I create a PR for version 1.2.0?

**Comment by clemensutschig** [comment]
@stitakis  -  1.1. is still untouched of this .. I would NOT add it into 1.1 except there is something currently brokeen .. let me know what you think

**Comment by stitakis** [comment]
@clemensutschig current BIX production branch includes this breaking change... I could introduce a backwards compatible change in BIX production branch and create a PR for 1.2 for this change, sounds good?

**Comment by michaelsauter** [comment]
A couple of notes:

1. This contains commit unrelated to what you describe, so I assume it is based off the wrong branch (it contains merge commits that look like you based your branch on `production`, not `master`).
2. I think we could make this less breaking by adding the old URL as a default into the YML.
3. This is a new feature, and therefore should only go into `master`, not `1.1.x`. The `x` indicates we only want to add patches ...

**Comment by stitakis** [comment]
@michaelsauter as discussed, we don´t need to introduce this change to 1.1.x... I´ll delete the PR

**Pull request closed without merging**
