### PR TITLE
added sonar-r-plugin

### PR DESCRIPTION
**Pull request by stevegbrooks**
This plugin from Merck <<https://github.com/Merck/sonar-r-plugin>> brings the R `lintr` package into sonarqube.

### CODE REVIEW

**Comment by gerardcl** [comment]
@michaelsauter could this be added already for 3.1?

**Review by gerardcl — APPROVED** [review]
LGTM!

**Comment by gerardcl** [comment]
before creating the PR to 3.x we should validate that there is no need for the lintr tool CLI mentioned in the docs.

**Comment by michaelsauter** [comment]
Nice 👍 

I would be fine with adding this into 3.1, as it looks backwards compatible. Any objections to this @borja44 @segator @metmajer?

On another note: should there be a `sonar-project.properties.template` now in the r-shiny quickstarter?

**Comment by gerardcl** [comment]
@michaelsauter correct! that should be a related change in ods-quickstarters

**Comment by segator** [comment]
I dont see any impediment/ risk to integrate to 3.1

**Pull request merged**
