### PR TITLE
Fix jenkins out of memory

### PR DESCRIPTION
**Pull request by hrcornejo**

### CODE REVIEW

**Comment by metmajer** [comment]
@michaelsauter @clemensutschig can this be merged?

**Comment by metmajer** [comment]
@hrcornejo where do the many changes come from? Please provide a slim PR that only contains what the title indicates.

**Comment by hrcornejo** [comment]
@metmajer my base branch were 2.x that's the reason because this PR has more changes

**Comment by michaelsauter** [comment]
@hrcornejo Then please cherry-pick your PR into a new branch based on 2.x

**Pull request closed without merging**
