### PR TITLE
Running E2E tests from local machine using AWS infrastructure

### PR DESCRIPTION
**Pull request by hugowschneider**
This is a Work In Progress for fixing the E2E test code and create a script for running the test in an AWS environment automatically from a local development environment.

### CODE REVIEW

**Comment by clemensutschig** [comment]
@hugowschneider  - how do we ensure there is as much as possible reuse from @georgfedermann 's work .. (largely PR: #549)

**Comment by hugowschneider** [comment]
@clemensutschig, the only focus here is to run the old tests again using VMs in AWS with the help with @michaelsauter.  That means we are trying run what is defined in the GitHub Actions workflow.

**Comment by michaelsauter** [comment]
@clemensutschig I was going through this with @hugowschneider earlier today.

I see it like this:

1. Get the tests back to a working state (executed manually on demand)
2. Make use of the scripts behind the `Makefile` targets to create the required OpenShift env to run the tests in. Those scripts are also used in #549. So that is how the reuse happens.
3. Extract anything that is still custom in the test setup and #549 into common scripts, which then also get a "Makefile interface" so that they can be run by admins (if applicable)

Apart from that, there are a couple of differences between this and #549 

- The dev VM should use the real software pieces, the tests mock most things (right now)
- The existing tests do not cover things end-to-end but serve as a smaller integration test

**Comment by clemensutschig** [comment]
I am totally happy .. :) just asking

**Comment by hugowschneider** [comment]
@clemensutschig, not yet. Some tests still need fixing and refactoring and the script to run the test in AWS is not ready also.

**Comment by michaelsauter** [comment]
@hugowschneider I think this should be merged now. It is in a state where one can reliable start an EC2 instance and execute tests in it.

That said, the tests fail right now:

* There's a diff on the `jenkins_edit` role, which is why the check is commented out. It appears that the `RoleBinding` creates a `ClusterRole`, whereas doing the same against a cluster that I have access to, it is a normal `Role`. Maybe it depends how executes it? The tests use an admin. I tried to force the role in the template, but to no avail.
* Running the `Jenkinsfile` doesn't work as the application is down

Even with failing tests I would want to merge this, as now everyone should be able to look at the problems and fix it, whereas without this PR you have to figure out lots by yourself.

**Comment by hugowschneider** [comment]
@michaelsauter Everything looks good and I agreed we should merge, and PR each test fix later on.

**Pull request merged**
