### PR TITLE
Jenkins master memory problem

### PR DESCRIPTION
**Pull request by victorpablosceruelo**
We need to do an evaluation of the correct parameters we need for a Jenkins master.
Tasks:

- [x] We need to fix problem reported in https://github.com/opendevstack/ods-core/issues/412
- [x] We need to take into account results from https://github.com/opendevstack/ods-core/pull/1160
- [x] We need to evaluate and take suggestions reported in https://github.com/opendevstack/ods-jenkins-shared-library/issues/857#issuecomment-1079631175

This might take some time.

### CODE REVIEW

**Comment by victorpablosceruelo** [comment]
We did a revision of the params we had in master branch vs the ones reported by @clemensutschig 

In master:
`-server -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1`

New proposal:
`-server -XX:NativeMemoryTracking=summary -XX:MaxRAMPercentage=90 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=256M -XX:SoftRefLRUPolicyMSPerMB=1`
`-Xms1024m -Xmx1g`

NOTE: xmx should be increased a little to get performance ( @clemensutschig )

Trying right now:
`-server -XX:NativeMemoryTracking=summary -XX:MaxRAMPercentage=90 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=256M -XX:SoftRefLRUPolicyMSPerMB=1 -XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1`
`-Xmx4g`

We'll have results in some hours.

**Comment by victorpablosceruelo** [comment]
More comments from the meeting we are having right now (after some testing):
If we assign to xmx 4gb, we need 2gb more, 1gb for Metaspace and another one for the host.
And -Xms1024m is a mandatory option.

**Comment by clemensutschig** [comment]
If you increase XMX - you also need to increase pod max memory ... and I removed the env vars for XMX and container heap percentage ..

```
sh-4.4$ jcmd 424 VM.native_memory summary

jcmd 424 VM.classloader_stats | grep Clean
```
where 424 is the process (via JPS)

**Comment by victorpablosceruelo** [comment]
@petod108, we are still waiting for your comments here.
Did you test the AMI image generated from the experimental branch?
Can you share here your results so we can evaluate if the solution is adequeate for the problem and we can merge it?
Thanks !!!

**Comment by metmajer** [comment]
@petod108 update please?

**Comment by petod108** [comment]
I didn't take whole AMI generated from http://ec2-54-155-126-35.eu-west-1.compute.amazonaws.com/job/ods-ci/job/ods-build-experimental-branch/

But in jenkins slave I set up setting of @clemensutschig month ago to following values: 
- name: JENKINS_MEMORY_LIMIT
  value: 4Gi
- name: JENKINS_MEMORY_REQUEST
  value: 2Gi
- name: JENKINS_CPU_LIMIT
  value: "1"
- name: JENKINS_JAVA_GC_OPTS
  value: "-server -XX:NativeMemoryTracking=summary -XX:MaxRAMPercentage=90 -XX:+UseG1GC -XX:+ExplicitGCInvokesConcurrent -XX:+ParallelRefProcEnabled -XX:+UseStringDeduplication -XX:MaxMetaspaceSize=1g -XX:MetaspaceSize=256M -XX:SoftRefLRUPolicyMSPerMB=1"

Which diferencies with this PR in 
 - name: JENKINS_MEMORY_LIMIT
   value: **6Gi**
- name: JENKINS_MEMORY_REQUEST
  value: **4Gi**
and **NOT** adding those options **-XX:+UnlockExperimentalVMOptions -XX:+UnlockDiagnosticVMOptions -XX:G1SummarizeRSetStatsPeriod=1**
into JENKINS_JAVA_GC_OPTS

The whole process of changing Jenkins-slave base on new AMI take like 1 day following manual instruction and executing whole tests to see if there is some error

**Comment by metmajer** [comment]
@petod108 which were the tests you were conducting or want to conduct? I only see you list the different attributes so far.

**Comment by metmajer** [comment]
@petod108 @jorge-romero @jafarre-viewnext please work on getting this done asap after vacations. Also, have a look at Peter's estimation and ensure we don't need 1 day to rebuild the Jenkins base agent.

**Comment by metmajer** [comment]
@petod108 @jorge-romero @jafarre-viewnext please work on getting this done asap after vacations. Also, have a look at Peter's estimation and make sure we don't need 1 day to rebuild the Jenkins base agent :| Environment variables are directly set at the Deployment Config of the Jenkins master.

**Comment by clemensutschig** [comment]
this is all jenkins master related - why are we talkingabout the agent here? @metmajer

**Comment by clemensutschig** [comment]
for me the master change seems reasonable .. the key is for the docs - if you increase XMX - you also need to increase the LIMITS :)

I would merge it - and then run the EDP tests against it, and put a similar fix into 4.x

**Comment by clemensutschig** [comment]
and the last piece to the puzzle:

image

**Comment by victorpablosceruelo** [comment]
> this is all jenkins master related - why are we talkingabout the agent here? @metmajer

@petod108 talks about slaves because he talks about the testing infrastructure. Inside the slave he talks about, he uses the AMI image to generate the whole environment. His master is the "always live" master in which we launch jobs for generating AMI images, running all the tests and something more.

I'm trying to include a draw that serves as base to understand what we have here:

Jenkins architecture

It seems to be this needs a huge refactoring applying the KISS ( Keep It Simple Stupid ) philosophy so we do not need to spend the huge amount of time we spend when we have to do modifications there, but we have too much work around to do this now. 

Right now we need to focus in what we need to fix: the configuration of the Jenkins master image that we use in the boxes.
I asked @petod108 to test this because the Jenkins version where you tested might be different from the one we use in the boxes. Since @petod108 is on holidays, we'll try to test it (and make it work) without him.

**Comment by victorpablosceruelo** [comment]
> and the last piece to the puzzle:
> 
> image

We do not have this yet in the AMI images (the other modifications are in the experimental branch). Since @clemensutschig  mentions it is the last piece of the puzzle, I'll try to see how to include it as first task.

**Comment by victorpablosceruelo** [comment]
Still checking if this will be enabled by default (this seems to be the case):

image

**Comment by clemensutschig** [comment]
nope - max durability is the defailt - you need to set it to mid ones .. and this ends up in the config.xml of the job ..

I would "guess" - that you can set it via jenkins job API ... ?! (which we could do from the shared lib, RM quickstarter provision)

**Comment by victorpablosceruelo** [comment]
More info on setting the durability parameter:

Configure the parameter using gui:
https://www.jenkins.io/doc/book/pipeline/scaling-pipeline/#:~:text=There%20are%203%20ways%20to%20configure%20the%20durability,override%20these%20with%20the%20more%20specific%20settings%20below.

Configure the parameter in the pipelines:
durabilityHint("MAX_SURVIVABILITY")
https://itnext.io/jenkins-tutorial-part-6-pipeline-options-5ccd05035aaf

Configure the docker image we use in opendevstack ods boxes:
https://github.com/openshift/jenkins/

**Comment by clemensutschig** [comment]
the challenge is that this is only in the declarative pipeline :(

```
pipeline {
    agent any
    options {
        buildDiscarder logRotator(
            artifactDaysToKeepStr: "30",
            artifactNumToKeepStr: "100",
            daysToKeepStr: "60",
```

**Comment by victorpablosceruelo** [comment]
This is where the jenkins docker img is configured:
https://github.com/opendevstack/ods-core/blob/master/jenkins/master/Dockerfile.centos7

And it seems to be using this:
https://github.com/cinqict/jenkins-init-groovy

Some pieces of code we could use:
https://www.tabnine.com/code/java/classes/org.jenkinsci.plugins.workflow.flow.GlobalDefaultFlowDurabilityLevel
https://github.com/jenkinsci/workflow-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/flow/GlobalDefaultFlowDurabilityLevel.java

And this works in the console ( https://jenkins-odsverify-cd.ocp.odsbox.lan/script ):
```
import org.jenkinsci.plugins.workflow.flow.*;
Jenkins j = Jenkins.instance

println(GlobalDefaultFlowDurabilityLevel.getDefaultDurabilityHint())
```

Lets check if the following snippet works:
```
import org.jenkinsci.plugins.workflow.flow.*;

FlowDurabilityHint fdh = FlowDurabilityHint.MAX_SURVIVABILITY;

Jenkins j = Jenkins.getInstanceOrNull()
def global_settings = j.getExtensionList(GlobalDefaultFlowDurabilityLevel.DescriptorImpl.class).get(0).durabilityHint = fdh;


println(GlobalDefaultFlowDurabilityLevel.getDefaultDurabilityHint())
```

It works, so we should be able to configure the Jenkins parameter when it runs the first time. 
What I have seen right now and I think I need to fix is the value: MAX_SURVIVABILITY ???
Here are the possible options:
https://github.com/jenkinsci/workflow-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowDurabilityHint.java

**Comment by victorpablosceruelo** [comment]
> the challenge is that this is only in the declarative pipeline :(
> 
> ```
> pipeline {
>     agent any
>     options {
>         buildDiscarder logRotator(
>             artifactDaysToKeepStr: "30",
>             artifactNumToKeepStr: "100",
>             daysToKeepStr: "60",
> ```
> 
> BINGO. https://stackoverflow.com/questions/47778019/how-to-use-options-in-a-jenkins-scripted-pipeline
> 
> So this should be doable in the RM jenkins pipeline itself I would guess

This is one of the options we have, but I really prefer putting the parameter into the Jenkins global options.
This way, if we need to change it in any pipeline we still can do it.
If it does not work we'll go for that option.

**Comment by victorpablosceruelo** [comment]
> nope - max durability is the defailt - you need to set it to mid ones .. and this ends up in the config.xml of the job ..
> 
> I would "guess" - that you can set it via jenkins job API ... ?! (which we could do from the shared lib, RM quickstarter provision)

I think MAX_SURVIVABILITY is the default and the one you told us to use is max durability, but I can't see it in 
https://github.com/jenkinsci/workflow-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/flow/FlowDurabilityHint.java

Still guessing why... :-(

**Comment by victorpablosceruelo** [comment]
If we run the following in the Jenkins console:
```
import org.jenkinsci.plugins.workflow.flow.*;
import hudson.model.Descriptor;

FlowDurabilityHint fdh = FlowDurabilityHint.MAX_SURVIVABILITY;

println("\nAvailable values: ")
for (FlowDurabilityHint maybeHint : FlowDurabilityHint.values()) {
  println(maybeHint)
}

println("\nPrevious value: ")
println(GlobalDefaultFlowDurabilityLevel.getDefaultDurabilityHint())

Jenkins j = Jenkins.getInstanceOrNull()
def global_settings = j.getExtensionList(GlobalDefaultFlowDurabilityLevel.DescriptorImpl.class).get(0).durabilityHint = fdh;

println("\nConfigured value: ")
println(GlobalDefaultFlowDurabilityLevel.getDefaultDurabilityHint())
```

We get:
```
Available values: 
PERFORMANCE_OPTIMIZED
SURVIVABLE_NONATOMIC
MAX_SURVIVABILITY

Previous value: 
MAX_SURVIVABILITY

Configured value: 
MAX_SURVIVABILITY
```

(I ran it multiple times. This is why previous and configured value are the same one)

**Comment by victorpablosceruelo** [comment]
Jenkins gui says this is the value we wanted ( MAX_SURVIVABILITY ). Maybe the name of the options is not good enough ?

image

Since the code does what we want, time to put it in the configuration folder, test and go on with the PR.

**Comment by clemensutschig** [comment]
the MAX_DURABILITY is the default -> so we need to set it to LOW or mid for the release manager ...!

**Comment by victorpablosceruelo** [comment]
> the MAX_DURABILITY is the default -> so we need to set it to LOW or mid for the release manager ...!

Could not understand... 

You said here (link below) we needed to set it to "Maximum durability but slowest", right ?
https://github.com/opendevstack/ods-core/pull/1161#issuecomment-1216877361

**Comment by clemensutschig** [comment]
the default is not set (=> max durability) - in order to prevent heavy serialization that hint needs to be set to low.

**Comment by victorpablosceruelo** [comment]
> the default is not set (=> max durability) - in order to prevent heavy serialization that hint needs to be set to low.

Then the perfect value would be PERFORMANCE_OPTIMIZED, which result is:

image

but I think this might be aggressive and dangerous.
What do you think about setting it to SURVIVABLE_NONATOMIC, which result is:

image

Or you are asking me to check which one is best?

**Comment by clemensutschig** [comment]
@victorpablosceruelo  - did you see any errors?

**Comment by victorpablosceruelo** [comment]
> @victorpablosceruelo - did you see any errors?

Hi @clemensutschig 
After a lot of testing, I have not seen any problem related to the memory problems we had in the past.
The configuration you provided seems to work perfectly.
Nevertheless, I'll continue with testing because some tests are not ending with success and this is something we must achieve.

**Comment by clemensutschig** [comment]
Very nice - can you paste the remaining errors, so I can take a look ;-)

**Comment by victorpablosceruelo** [comment]
Yep, of course.
The important part of logs are below, and you can get the full logs from
https://ods-ci.apps.bix-digital.com/job/edp-e2e-tests/job/e2e/job/master/ 

Doing another revision, it seems to be I did not saw the following one:

```
22:13:46  com.bi.edp.e2e.MultipleTestsSpec
22:13:46  
22:13:46    Test EDPC884 Multiple E2E tests components FAILED (55m 15s)
22:13:46  
22:13:46    java.lang.RuntimeException: Error: unable to get Jenkins log. Jenkins responded with status: '404 Not Found' and message: '<html>
22:13:46    <head>
22:13:46    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
22:13:46    <title>Error 404 Not Found</title>
22:13:46    </head>
22:13:46    <body><h2>HTTP ERROR 404</h2>
22:13:46    <p>Problem accessing /job/tes59-cd/job/tes59-cd-releasemanager-master/lastBuild/consoleText. Reason:
22:13:46    <pre>    Not Found</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>
22:13:46    
22:13:46    </body>
22:13:46    </html>
22:13:46    '.
22:13:46        at com.bi.edp.e2e.MultipleTestsSpec.setup(MultipleTestsSpec.groovy:22)
```

I do not like it, because I have no information on what caused Jenkins to die. Maybe still the memory problem? Need to investigate this one a little bit more...

About the others, below is a classification by error type.

Some of them are related to the tests code itself -- Field that we wait for and is no more available.

[EDPJiraLinksSpec, JiraReleaseManagerSpec, EDPProjectPropertiesSpec, DeveloperPreviewSpec, ThreeVersionsRelManTestsSpec, UnitErrorTestsSpec, VersioningCreateFromStorySpec, VersioningDiscontinueAnIssueBisSpec, VersioningDiscontinueAnIssueSpec, VersioningIssueBehaviorsSpec, VersioningSupersedingAnIssueSpec, VersioningViaReleasePageSpec]
```
22:20:15    geb.waiting.WaitTimeoutException: condition did not pass in 120 seconds. Failed with exception:
22:20:15    java.lang.NullPointerException: Cannot invoke method contains() on null object
22:20:15        at com.bi.edp.e2e.DeveloperPreviewSpec.EDPC1299 Test developer preview(DeveloperPreviewSpec.groovy:20)
22:20:15    Caused by: java.lang.NullPointerException: Cannot invoke method contains() on null object
22:20:15        at com.bi.edp.e2e.DeveloperPreviewSpec.EDPC1299 Test developer preview(DeveloperPreviewSpec.groovy:20)
```

[JiraReleaseManagerSpec] -- Button that maybe is blocked in new workflows
```
22:45:08    Test RT_09_001 FAILED (1m 14s)
22:45:08  
22:45:08    org.openqa.selenium.ElementClickInterceptedException: element click intercepted: Element <button class="aui-button  helptip-close" type="button" resolved="">...</button> is not clickable at point (1281, 183). Other element would receive the click: <a target="_blank" href="#" class="aui-button aui-button-link" id="base-url-proxy-config-fix" resolved="">...</a>
22:45:08      (Session info: headless chrome=104.0.5112.101)
22:45:08    Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
22:45:08    System info: host: 'Unknown', ip: 'Unknown', os.name: 'Linux', os.arch: 'amd64', os.version: '3.10.0-1160.76.1.el7.x86_64', java.version: '11.0.11'
22:45:08    Driver info: org.openqa.selenium.chrome.ChromeDriver
22:45:08    Capabilities {acceptInsecureCerts: true, browserName: chrome, browserVersion: 104.0.5112.101, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: /tmp/.com.google.Chrome.RSxEbd}, goog:chromeOptions: {debuggerAddress: localhost:43568}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
22:45:08    Session ID: 43d06902b91a4e423893609ba7324490
22:45:08        at com.bi.edp.e2e.release.RT09001Scenario.RT_09_001(RT09001Scenario.groovy:20)
```

Some others are network related -- we might need retries
[EDPProjectProvisioningSpec, IssueEDPButtonsSpec]
```
21:11:20  [INFO] Unable to get build host, skipping property build.host. Error message: ip-172-31-25-105.eu-west-1.compute.internal: ip-172-31-25-105.eu-west-1.compute.internal: Name or service not known
```

Or maybe setting the correct key to access repositories
[EDPProjectProvisioningSpec, IssueEDPButtonsSpec]
```
21:04:48  ERROR: Error fetching remote repo 'origin'
21:04:48  hudson.plugins.git.GitException: Failed to fetch from ssh://git@bitbucket.biscrum.com:7999/edpc/edp-import-export-projects.git
21:04:48  	at hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:1003)
21:04:48  	at hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1244)
21:04:48  	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1308)
21:04:48  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:129)
21:04:48  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:97)
21:04:48  	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:84)
21:04:48  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
21:04:48  	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
21:04:48  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
21:04:48  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
21:04:48  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
21:04:48  	at java.base/java.lang.Thread.run(Thread.java:829)
21:04:48  Caused by: hudson.plugins.git.GitException: Command "git fetch --tags --force --progress -- ssh://git@bitbucket.biscrum.com:7999/edpc/edp-import-export-projects.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
21:04:48  stdout: 
21:04:48  stderr: ssh_exchange_identification: read: Connection reset by peer
21:04:48  fatal: Could not read from remote repository.
```

They are a lot. We'll try to fix them ASAP...

**Comment by victorpablosceruelo** [comment]
The problem is the following one:

image

```
2022-09-08 14:46:19.370+0000 [id=28]	WARNING	j.util.groovy.GroovyHookScript#execute: Failed to run script file:/var/lib/jenkins/init.groovy.d/flow-durability-hint.groovy
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/var/lib/jenkins/init.groovy.d/flow-durability-hint.groovy: 14: unable to resolve class Jenkins 
 @ line 14, column 9.
   Jenkins j = Jenkins.getInstanceOrNull()
           ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:958)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:605)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:554)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:584)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:136)
	at jenkins.util.groovy.GroovyHookScript.execute(GroovyHookScript.java:127)
	at jenkins.util.groovy.GroovyHookScript.run(GroovyHookScript.java:110)
	at hudson.init.impl.GroovyInitScript.init(GroovyInitScript.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:104)
	at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
	at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
	at jenkins.model.Jenkins$5.runTask(Jenkins.java:1121)
	at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
	at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2022-09-08 14:46:19.372+0000 [id=28]	INFO	j.util.groovy.GroovyHookScript#execute: Executing /var/lib/jenkins/init.groovy.d/ods-jenkins-shared-library.groovy
```

But don't know why this was not detected in testing boxes...

**Comment by victorpablosceruelo** [comment]
This is what we are missing...
```
All the classes from all the plugins are visible. jenkins.*, jenkins.model.*, hudson.*, and hudson.model.* are pre-imported.
```

Solution: 
https://github.com/opendevstack/ods-core/pull/1181/files#diff-0b5cf352b492809717138b6ca9ef784a4b142752f551198380646cced1b286cbR1

**Comment by victorpablosceruelo** [comment]
Maybe it should be considered adding for the pods the memory management options in the following link?
https://stackoverflow.com/questions/52555036/do-java-flags-xms-and-xmx-overwrite-flag-xxusecgroupmemorylimitforheap

Since we had to remove `-XX:+UseCGroupMemoryLimitForHeap` in the slaves configuration because we are using java 11 for pods right now, maybe this is interesting...

I mean using one or more of: InitialRAMPercentage, MaxRAMPercentage and MinRAMPercentage
More info: https://www.merikan.com/2019/04/jvm-in-a-container/

**Comment by victorpablosceruelo** [comment]
Now it is working as expected:

image

This comes from a Box during the creation process, launched before latest fixes. 
Now that we introduced upgrade of golangci-lint and fixes in the code we should be able to obtain a working box.

**Pull request merged**
