### PR TITLE
#EDPC-1041 Test steps don't show up in the deltadocgen report on boxes

### PR DESCRIPTION
**Pull request by angelmp01**
- Configured mysql container by setting sql-mode to ANSI_QUOTES to accept querys with double quotes in column and tables name

### CODE REVIEW

**Review by s2oBCN — DISMISSED** [review]

**Comment by angelmp01** [comment]
Hi @michaelsauter could you check the Jenkins agent base test error?

**Comment by michaelsauter** [comment]
So the test failure is definitely unrelated to your change.

I do not understand yet why it fails exactly. The last [successful build](https://github.com/opendevstack/ods-core/runs/4151140650?check_suite_focus=true) on `master` was 16 days ago, and nothing relevant has changed in `ods-core` since then.

Googling revealed the following so far:

* https://access.redhat.com/solutions/5446851: sounds similar at first but the actual problem there is a deprecated package
* https://www.aclnz.com/interests/blogs/transaction-check-error-file-etc-pki-rpm-gpg-rpm-gpg-key-from-install: again, sounds similar

My gut feeling right now is that it is related to the `centos8-appstream` repository. It is very unfortunate that we (need?) to use this repo. I am going to try and reproduce this locally but can't promise anything.

**Comment by michaelsauter** [comment]
Oh, forgot to mention that this seems to be due to an update of skopeo/containers-common.

Successful build:
```
Installing:
 skopeo              x86_64  1:1.3.1-5.module_el8.4.0+886+c9a8d9ad     centos-appstream  7.0 M
Installing dependencies:
 containers-common   x86_64  1:1.3.1-5.module_el8.4.0+886+c9a8d9ad     centos-appstream   95 k
```

Failing build:
```
Installing:
 skopeo                       x86_64            1:1.4.2-0.1.module_el8.5.0+911+f19012f9               centos-appstream            6.7 M
Installing dependencies:
 containers-common            noarch            2:1-2.module_el8.5.0+890+6b136101                     centos-appstream             79 k
```

I wonder why it says `noarch` there ...

**Comment by michaelsauter** [comment]
Uh, I believe this to be an error in the CentOS repository.

I had a look into http://mirror.centos.org/centos/8/AppStream/x86_64/os/repodata/dccfb990438ca7092f91092de5117151d600391b81f1315b1804c6fea0f8b4ff-primary.xml.gz. This has the following two relevant entries:

```
<package type="rpm">
  <name>containers-common</name>
  <arch>x86_64</arch>
  <version epoch="1" ver="0.1.41" rel="4.module_el8.5.0+1004+c00a74f5"/>
  <checksum type="sha256" pkgid="YES">53c48e2ee040a1815d52c068ede4e942101a692c170745a6ee73a771cffda2bf</checksum>
  <summary>Configuration files for working with image signatures</summary>
  <description>This package installs a default signature store configuration and a default
policy under `/etc/containers/`.</description>
  <packager>CentOS Buildsys &lt;bugs@centos.org&gt;</packager>
  <url>https://github.com/containers/skopeo</url>
  <time file="1636514945" build="1636509217"/>
  <size package="51701" installed="44771" archive="48660"/>
  <location href="Packages/containers-common-0.1.41-4.module_el8.5.0+1004+c00a74f5.x86_64.rpm"/>
```

```
<package type="rpm">
  <name>containers-common</name>
  <arch>noarch</arch>
  <version epoch="2" ver="1" rel="2.module_el8.5.0+890+6b136101"/>
  <checksum type="sha256" pkgid="YES">1b008504f4a541720e47cdf73fa384271c59314c12e7b5d9cc7d0481ef81debb</checksum>
  <summary>Common configuration and documentation for containers</summary>
  <description>This package contains common configuration files and documentation for container
tools ecosystem, such as Podman, Buildah and Skopeo.

It is required because the most of configuration files and docs come from projects
which are vendored into Podman, Buildah, Skopeo, etc. but they are not packaged
separately.</description>
  <packager>CentOS Buildsys &lt;bugs@centos.org&gt;</packager>
  <url></url>
  <time file="1629327596" build="1629326616"/>
  <size package="80919" installed="241307" archive="247008"/>
  <location href="Packages/containers-common-1-2.module_el8.5.0+890+6b136101.noarch.rpm"/>
```

Running `yum list containers-common` yields:
```
containers-common.noarch                            2:1-2.module_el8.5.0+890+6b136101                                   centos-appstream
```

It doesn't show the `x86_64` package :(

If one downloads the `x86_64` package manually (`curl -LO http://mirror.centos.org/centos/8/AppStream/x86_64/os/Packages/containers-common-1.2.2-10.module_el8.5.0+1006+8d0e68a2.x86_64.rpm`) and then installs it manually (`rpm -i containers-common-1.2.2-10.module_el8.5.0+1006+8d0e68a2.x86_6.rpm`), no error is reported. Unfortunately, a subsequent `yum install skopeo` tries to "upgrade" `containers-common`, which fails again.

I am not sure what we can do for an immediate fix. Maybe we can report this problem somewhere with CentOS?

**Comment by angelmp01** [comment]
@michaelsauter Do you know why we are using yum and not dnf to install skopeo? I don't know if it can affect

**Comment by michaelsauter** [comment]
@angelmp01 AFAIK `yum` is an alias to `dnf` in this image. See:

```
bash-4.4# yum --version
Failed to set locale, defaulting to C.UTF-8
4.4.2
  Installed: dnf-0:4.4.2-11.el8.noarch at Tue Oct 26 12:59:23 2021
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Mon Mar  8 15:43:15 2021

  Installed: rpm-0:4.14.3-14.el8_4.x86_64 at Tue Oct 26 12:59:17 2021
  Built    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla> at Mon May 31 16:43:19 2021
```

**Comment by angelmp01** [comment]
@michaelsauter I've changed the skopeo installation for ubi8 using your suggestion to manually download package containers-common. I needed to update the skopeo version. Please check it out

**Review by s2oBCN — APPROVED** [review]

**Pull request merged**
