### PR TITLE
agent base image use ubi repos and cleanup non working

### PR DESCRIPTION
**Pull request by gerardcl**
port of https://github.com/opendevstack/ods-core/pull/1106

### CODE REVIEW

**Comment by tbugfinder** [comment]
Currently epel is used in terraform agent. Could this repo be already added in this agent and kept disabled?

**Comment by gerardcl** [comment]
> Currently epel is used in terraform agent. Could this repo be already added in this agent and kept disabled?

why not add this only in terraform if only required there? anyway I will take a look too 👍

**Comment by gerardcl** [comment]
@tbugfinder are you talking about centos7 or ubi8 Dockerfile?

**Comment by tbugfinder** [comment]
> @tbugfinder are you talking about centos7 or ubi8 Dockerfile?

I'd like to focus on ubi8 only.
This can be done in terraform agent itself, just asking for clarification as the base image might be used by different downstream builds.

**Comment by gerardcl** [comment]
then my suggestion would be that meanwhile it is not a general requirement but specific to terraform we add it in the terraform one (I confirm it is only used in this one for now)

**Pull request merged**
