### PR TITLE
initial draft version for Ubuntu 16.04 based ODS setup script

### PR DESCRIPTION
**Pull request by georgfedermann**
I've been working on a script that can be executed on a fresh Ubuntu 16.04 LTS VM (including git client) to setup an ODS development environment on a remote workstation, thus including the Atlassian tool suite, Nexus, etc. This initial version of the script goes as far as to setup an OpenShift cluster.

I'd like to align the efforts. Is this approach going into the right direction? What have I been missing? Who else should be invited as a reviewer?
Thanks for your feedback!

### CODE REVIEW

**Comment by michaelsauter** [comment]
Adding @hugowschneider in the loop as he did some work related to this in the test setup.

**Comment by georgfedermann** [comment]
I'm experiencing problems with the setup sequence as taken from continuous-integration-workflow.yml:
When I setup an Ubuntu 16.04 VM as specified and in the end run
`oc cluster up`
I get a working OpenShift cluster running all the expected pods. When running
`oc get pods --all-namespaces`
I see among others:
`openshift-web-console           webconsole-6fb979d45d-qqvxd                               1/1       Running     0          2h`
and I am able to log into the WebConsole with various users (developer, admin).
But when I setup an Ubuntu 16.04 VM as specified and in the end run 
`oc cluster up --base-dir=${HOME}/openshift.local.clusterup --routing-suffix 172.17.0.1.nip.io --public-hostname 172.17.0.1 --enable=centos-imagestreams --enable=persistent-volumes --enable=registry --enable=router`
then the OpenShift cluster will still startup and I will be able to work with it via the oc cli tools, but the pod running the WebConsole does not start anymore. Thus, no WebConsole is available. Is this a known issue? Do we already know a solution for this?

ifconfig shows that there is a network docker0 with the specified inet addr 172.17.0.1.

**Comment by clemensutschig** [comment]
@georgfedermann  - we kicked out the webconsole - to save memory .. that was intended :)

**Comment by georgfedermann** [comment]
> @georgfedermann - we kicked out the webconsole - to save memory .. that was intended :)

ah yes, of course. That's the reason! Thanks :)

**Comment by clemensutschig** [comment]
Status?

**Comment by georgfedermann** [comment]
This approach has been rendered obsolete by a different setup script which as a first milestone provides an ODS test environment running on AWS EC2 or VMs local to developer workstations. Will close this PR.

**Pull request closed without merging**
