### PR TITLE
fix sonarqube libressl issue - move to openssl

### LINKED ISSUE #996: sonarqube build fails on ODS 3.x
**Describe the bug**
When building latest Dockerfile for sonarqube with ODS 3.x branch it fails. 

**To Reproduce**
1. Go to 'cd sonarqube/docker/'
2. Trigger local or openshift docker build
3. Build fails
4. See error log below

**Expected behavior**
Build should work

**Screenshots**
N/A

**Affected version (please complete the following information):**
 - OpenShift: all
 - OpenDevStack 3.x

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**

```bash
STEP 9: RUN set -x     && apk update     && apk add --no-cache ca-certificates     && apk add --no-cache gnupg unzip     && apk add --no-cache libressl wget     && apk add --no-cache su-exec     && apk add --no-cache bash     && mkdir -p /opt     && cd /opt     && wget -O sonarqube.zip --no-verbose $sonarDistributionUrl     && unzip sonarqube.zip     && mv sonarqube-$SONAR_VERSION sonarqube     && chown -R sonarqube:root sonarqube     && chmod -R g+w sonarqube     && rm sonarqube.zip*     && rm -rf $SONARQUBE_HOME/bin/*     && mkdir -p /opt/configuration/sonarqube     && chown -R sonarqube:root /opt/configuration/sonarqube
time="2021-07-07T14:20:45Z" level=warning msg="Path \"/run/secrets/etc-pki-entitlement\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
time="2021-07-07T14:20:45Z" level=warning msg="Path \"/run/secrets/redhat.repo\" from \"/etc/containers/mounts.conf\" doesn't exist, skipping"
+ apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.0-70-gd0f9887ff3 [https://dl-cdn.alpinelinux.org/alpine/v3.14/main]
v3.14.0-104-gc7adf21e09 [https://dl-cdn.alpinelinux.org/alpine/v3.14/community]
OK: 14932 distinct packages available
+ apk add --no-cache ca-certificates
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ca-certificates (20191127-r5)
Executing busybox-1.33.1-r2.trigger
Executing ca-certificates-20191127-r5.trigger
OK: 18 MiB in 18 packages
+ apk add --no-cache gnupg unzip
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/29) Installing libgpg-error (1.42-r0)
(2/29) Installing libassuan (2.5.5-r0)
(3/29) Installing libcap (2.50-r0)
(4/29) Installing libffi (3.3-r2)
(5/29) Installing libintl (0.21-r0)
(6/29) Installing libblkid (2.37-r0)
(7/29) Installing libmount (2.37-r0)
(8/29) Installing pcre (8.44-r0)
(9/29) Installing glib (2.68.2-r0)
(10/29) Installing ncurses-terminfo-base (6.2_p20210612-r0)
(11/29) Installing ncurses-libs (6.2_p20210612-r0)
(12/29) Installing libgcrypt (1.9.3-r0)
(13/29) Installing libsecret (0.20.4-r1)
(14/29) Installing pinentry (1.1.1-r0)
Executing pinentry-1.1.1-r0.post-install
(15/29) Installing libbz2 (1.0.8-r1)
(16/29) Installing gmp (6.2.1-r0)
(17/29) Installing nettle (3.7.2-r0)
(18/29) Installing p11-kit (0.23.22-r0)
(19/29) Installing libtasn1 (4.17.0-r0)
(20/29) Installing libunistring (0.9.10-r1)
(21/29) Installing gnutls (3.7.1-r0)
(22/29) Installing libksba (1.5.1-r0)
(23/29) Installing gdbm (1.19-r0)
(24/29) Installing libsasl (2.1.27-r12)
(25/29) Installing libldap (2.4.58-r0)
(26/29) Installing npth (1.6-r0)
(27/29) Installing sqlite-libs (3.35.5-r0)
(28/29) Installing gnupg (2.2.27-r0)
(29/29) Installing unzip (6.0-r9)
Executing busybox-1.33.1-r2.trigger
Executing glibc-bin-2.33-r0.trigger
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

OK: 38 MiB in 47 packages
+ apk add --no-cache libressl wget
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
(1/6) Installing libressl3.3-libcrypto (3.3.3-r0)
(2/6) Installing libressl3.3-libssl (3.3.3-r0)
(3/6) Installing libressl3.3-libtls (3.3.3-r0)
ERROR: libressl3.3-libtls-3.3.3-r0: trying to overwrite usr/lib/libtls.so.20 owned by libretls-3.3.3-r0.
ERROR: libressl3.3-libtls-3.3.3-r0: trying to overwrite usr/lib/libtls.so.20.0.3 owned by libretls-3.3.3-r0.
(4/6) Installing libressl (3.3.3-r0)
(5/6) Installing libidn2 (2.3.1-r0)
(6/6) Installing wget (1.21.1-r1)
Executing busybox-1.33.1-r2.trigger
Executing glibc-bin-2.33-r0.trigger
/usr/glibc-compat/sbin/ldconfig: /usr/glibc-compat/lib/ld-linux-x86-64.so.2 is not a symbolic link

1 error; 43 MiB in 53 packages
error: build error: error building at STEP "RUN set -x     && apk update     && apk add --no-cache ca-certificates     && apk add --no-cache gnupg unzip     && apk add --no-cache libressl wget     && apk add --no-cache su-exec     && apk add --no-cache bash     && mkdir -p /opt     && cd /opt     && wget -O sonarqube.zip --no-verbose $sonarDistributionUrl     && unzip sonarqube.zip     && mv sonarqube-$SONAR_VERSION sonarqube     && chown -R sonarqube:root sonarqube     && chmod -R g+w sonarqube     && rm sonarqube.zip*     && rm -rf $SONARQUBE_HOME/bin/*     && mkdir -p /opt/configuration/sonarqube     && chown -R sonarqube:root /opt/configuration/sonarqube": error while running runtime: exit status 1
```

**Additional context**
The error is related to libressl not working with latest alpine version changes. Suggestion is to move to openssl, which also is detected with no vulnerabilities known so far with the given version.
We might want also this to be on master so to have consistency on the tooling used.

### PR DESCRIPTION
**Pull request by gerardcl**
fixes #996

### CODE REVIEW

**Comment by gerardcl** [comment]
@braisvq1996 FYI 👍

**Review by clemensutschig — APPROVED** [review]
Master as well ? @gerardcl

**Comment by gerardcl** [comment]
indeed @clemensutschig , just checked and also same issue, will update issue and promote fix

**Comment by gerardcl** [comment]
@braisvq1996 should we also promote the openssl change to master?

**Comment by braisvq1996** [comment]
@gerardcl - it should be ok to apply this change to master as well so that we mantain consistency as you mention

**Pull request merged**
