### PR TITLE
Renamed configmap to prov-app.properties

### PR DESCRIPTION
**Pull request by felipecruz91**
Refers to #757

### CODE REVIEW

**Comment by michaelsauter** [comment]
Do you know if we should also change something in the `ods-provisioning-app` repo to align with this change?

**Comment by clemensutschig** [comment]
@stitakis - is there anything you see a problem with? ...

**Comment by stitakis** [comment]
@clemensutschig renaming to something else could have an impact in the way spring boot recognize the configuration file. There are ways to change the naming default. I need to take a look at it.

**Comment by felipecruz91** [comment]
@stitakis ping

**Comment by stitakis** [comment]
@felipecruz91 I'm busy atm with the coming release of ODS 3.1.0... I'll take a look at this once the release is done... sounds good?

**Comment by stitakis** [comment]
@felipecruz91 changing this will probably require to do a change in prov-app... therefore to avoid any mistake of merging this to early I propose to move this branch to draft status, ok?

**Comment by felipecruz91** [comment]
@stitakis it makes sense, no probs

**Comment by stitakis** [comment]
Not needed at the moment. Closed

**Pull request closed without merging**
