### PR TITLE
Add sonar-apex-plugin for SonarQube Enterprise and Datacenter editions

### PR DESCRIPTION
**Pull request by braisvq1996**
This is the initial PR for the issue #975

There is an issue where this plugin gives errors when adding it to Sonar Community and Developer editions.
This plugin can only be added to Enterprise and Datacenter editions
https://docs.sonarqube.org/8.2/analysis/languages/overview/

That is why we had to make a difference between the editions and add an if statement into the dockerfile

If you have any thoughts on this please share them

@metmajer @felipecruz91 @michaelsauter @gerardcl

### CODE REVIEW

**Review by clemensutschig — CHANGES_REQUESTED** [review]
there is a test missing ... where plugins are checked

**Comment by felipecruz91** [comment]
@braisvq1996 @clemensutschig The SonarQube tests are failing as the test suite uses a [non-commercial distribution](https://github.com/opendevstack/ods-core/blob/30f3966cc80df9078a2a853d58581da024f97539/sonarqube/test.sh#L56) of SonarQube.

Therefore, the `apex:1.8.2.1946` plugin shall be removed from the `expectedPlugins` [list](https://github.com/opendevstack/ods-core/blob/30f3966cc80df9078a2a853d58581da024f97539/sonarqube/test.sh#L193).

**Comment by michaelsauter** [comment]
@felipecruz91 Would be great if we can have a commercial edition under test as well. I suggest to try what you suggested in a separate PR, and then have this PR be based on that.

**Comment by clemensutschig** [comment]
@braisvq1996  - do you fix this one now as well

**Comment by braisvq1996** [comment]
@clemensutschig - Yeah, that is the plan.

**Review by clemensutschig — APPROVED** [review]

**Pull request merged**
