### PR TITLE
removed/replaced redundant PROV_APP_PIPELINE_TRIGGER_SECRET

### LINKED ISSUE #722: PROV_APP_PIPELINE_TRIGGER_SECRET seems to be redundant
**Is your feature request related to a problem? Please describe.**
The property [PROV_APP_PIPELINE_TRIGGER_SECRET](PROV_APP_PIPELINE_TRIGGER_SECRET) seems to be redundant, since there is already [PIPELINE_TRIGGER_SECRET](PIPELINE_TRIGGER_SECRET) 

**Describe the solution you'd like**
- Remove PROV_APP_PIPELINE_TRIGGER_SECRET  from https://github.com/opendevstack/ods-core/blob/master/configuration-sample/ods-core.env.sample#L276
- Replace PROV_APP_PIPELINE_TRIGGER_SECRET by PIPELINE_TRIGGER_SECRET in https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/cm.yml#L59 and https://github.com/opendevstack/ods-core/blob/master/ods-provisioning-app/ocp-config/cm.yml#L208

### PR DESCRIPTION
**Pull request by renedupont**
fixes #722

### CODE REVIEW

**Comment by michaelsauter** [comment]
FYI @segator @borja44 This will affect the docs, right? They list this param? Maybe it would be good to check, after this PR is merged, if the docs reflect the actual param (names).

**Comment by segator** [comment]
Maybe anyway change this is not a problem :)

@borja44 can you double confirm?

**Comment by michaelsauter** [comment]
@georgfedermann I tried to figure out how this param is populated for the EDP box. But it does not seem to be set in `create_configuration()` - do you know more about it?

**Comment by georgfedermann** [comment]
@michaelsauter actually, it gets set in create_configuration() as a side effect of setting PIPELINE_TRIGGER_SECRET.
Actually a bug that did not cause any effect and went undiscovered so far.

**Pull request merged**
